name: Bug 反馈
description: Bug 反馈
title: "[Bug]: "
labels: ["bug"]
assignees:
  - normalcoder
body:
  - type: checkboxes
    attributes:
      label: 这个问题是否已经存在？
      options:
        - label: 我已经搜索过 [现有的问题](../issues)，无重复问题出现
          required: true
  - type: textarea
    attributes:
      label: 如何复现
      description: 请详细告诉我们如何复现你遇到的问题。如果可以的话，上传任何关于 bug 的截图。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 预期结果
      description: 请告诉我们你预期会发生什么。
    validations:
